namespace Entities
{
    /// <summary> => this serves as documentation. it is generated by 3 of '/'. Note that this model will not be directly send to the presentation layer (actual runnable project) You will use a DTO for that
    /// Domain Model for Country
    /// </summary>
    public class Country
    {
        public Guid CountryId { get; set; }
        public string? CountryName { get; set; }
    }
}